finish exercise
devtanole/m1-0724-code-solutions pull request #7
Opened 2024-07-14 21:02 UTC by devtanole

<img width="1792" alt="Screenshot 2024-07-14 at 2 02 09 PM" src="https://github.com/user-attachments/assets/1109cc46-6fc7-49b6-9c7c-68c3d03fb07b">

2024-07-14 21:56 UTC, hesam requested changes
This is good work! If possible, see if you could improve (generalize) it by taking advantage of arrays! Rather than product1 product2 properties, how about using a property called products which stores any number of items which happen to be inside an order... You'll have to define a second new interface to represent each product.

2024-07-15 07:59 UTC, devtanole commented
<img width="1792" alt="Screenshot 2024-07-15 at 12 59 01 AM" src="https://github.com/user-attachments/assets/819da31d-b89f-4a30-8488-6cac728c915b">

2024-07-15 13:28 UTC, hesam commented on typescript-data-model/order-history.ts
> +// interface product {prodArr: [{prodName: string; author?: string; prodTotal: number;}];}
interface product {prodName: string; author?: string; prodTotal: number;}

2024-07-15 13:29 UTC, hesam commented on typescript-data-model/order-history.ts
> +  prodArr: any[];
prodArr: product[];

2024-07-15 13:30 UTC, hesam requested changes
Almost there. I left 2 comments inside your code to fix...

2024-07-15 17:48 UTC, hesam approved these changes
Nice. Be sure to include the changes I commented earlier. 👍

2024-07-16 05:46 UTC, merged